application: ostatus-unofficial
version: 1
threadsafe: false
api_version: 1
default_expiration: 1d

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# dynamic
- url: /(.well-known/.*|delete)?
  script: app.py
  secure: always

- url: /facebook/.*
  script: facebook.py
  login: required
  secure: always

- url: /googleplus/.*
  script: googleplus.py
  login: required
  secure: always

- url: /twitter/.*
  script: twitter.py
  login: required
  secure: always

- url: /oauth2callback
  script: oauth2client/appengine.py
  secure: always

- url: /_ah/queue/.*
  script: tasks.py
  login: admin
  
- url: /.+
  script: ostatus.py
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the submodule subdirs, especially since
# webapp-improved/lib has over 1k files and feedparser/tests has over 2.3k!
- ^feedparser/(docs|feedparser/tests)/.*
- ^google-api-python-client/(docs|samples|tests)/.*
- ^webutil/webapp-improved/.*/.*
